$(document).ready(function () {
    var c = document.getElementById("rpm_us"), z = new Chart(c, { type: "bar", data: {}, options: { responsive: !0, maintainAspectRatio: !1, scales: { xAxes: [{ label: [], ticks: { autoSkip: !0 } }], yAxes: [{ label: [], position: "left", id: "A", ticks: { beginAtZero: !0, stepSize: 1 } }] } } }); c = document.getElementById("rpm_ca"); var A = new Chart(c, {
        type: "bar", data: {}, options: {
            responsive: !0, maintainAspectRatio: !1, scales: {
                xAxes: [{ label: [], ticks: { autoSkip: !0 } }], yAxes: [{
                    label: [], position: "left", id: "A", ticks: {
                        beginAtZero: !0,
                        stepSize: 1
                    }
                }]
            }
        }
    }); c = document.getElementById("rpm_gb"); var B = new Chart(c, { type: "bar", data: {}, options: { responsive: !0, maintainAspectRatio: !1, scales: { xAxes: [{ label: [], ticks: { autoSkip: !0 } }], yAxes: [{ label: [], position: "left", id: "A", ticks: { beginAtZero: !0, stepSize: 1 } }] } } }); c = document.getElementById("rpm_in"); var C = new Chart(c, { type: "bar", data: {}, options: { responsive: !0, maintainAspectRatio: !1, scales: { xAxes: [{ label: [], ticks: { autoSkip: !0 } }], yAxes: [{ label: [], position: "left", id: "A", ticks: { beginAtZero: !0, stepSize: 1 } }] } } });
    c = document.getElementById("rpm_other"); var D = new Chart(c, { type: "bar", data: {}, options: { responsive: !0, maintainAspectRatio: !1, scales: { xAxes: [{ label: [], ticks: { autoSkip: !0 } }], yAxes: [{ label: [], position: "left", id: "A", ticks: { beginAtZero: !0, stepSize: 1 } }] } } }); (function () {
        $.ajax({
            url: "/Revenue/GeoAdAge", type: "get", dataType: "json", success: function (c) {
                ajaxData = c; for (var b = 0, d = 0, e = 0, f = 0, g = 0, h = 0, k = 0, l = 0, m = 0, n = [], p = [], q = [], r = [], t = [], u = [], v = [], w = [], x = [], y = [], a = 0; a < c.Date.length; a++) "US" == ajaxData.Country[a] && ("ContentAd" ==
                ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (p[b] = [ajaxData.RPM[a]], n[b] = [ajaxData.Date[a]], b++), "ContentAd" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (q[d] = [ajaxData.RPM[a]], d++), "ContentAd" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (r[e] = [ajaxData.RPM[a]], e++), "MGID" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (t[f] = [ajaxData.RPM[a]], f++), "MGID" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (u[g] = [ajaxData.RPM[a]], g++), "MGID" == ajaxData.Advertiser[a] &&
                "22+" == ajaxData.AgeBucket[a] && (v[h] = [ajaxData.RPM[a]], h++), "RevContent" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (w[k] = [ajaxData.RPM[a]], k++), "RevContent" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (x[l] = [ajaxData.RPM[a]], l++), "RevContent" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (y[m] = [ajaxData.RPM[a]], m++)); z.data.labels = n; z.data.datasets[0] = { label: ["ContentAd:0-7"], backgroundColor: "transparent", borderColor: "red", borderDash: [5, 5], data: p, type: "line" }; z.data.datasets[1] =
                { label: ["ContentAd:8-21"], backgroundColor: "transparent", borderColor: "red", borderDash: [2, 2], data: q, type: "line" }; z.data.datasets[2] = { label: ["ContentAd:22+"], backgroundColor: "transparent", borderColor: "red", data: r, type: "line" }; z.data.datasets[3] = { label: ["MGID:0-7"], backgroundColor: "transparent", borderColor: "blue", borderDash: [5, 5], data: t, type: "line" }; z.data.datasets[4] = { label: ["MGID:8-21"], backgroundColor: "transparent", borderColor: "blue", borderDash: [2, 2], data: u, type: "line" }; z.data.datasets[5] = {
                    label: ["MGID:22+"],
                    backgroundColor: "transparent", borderColor: "blue", data: v, type: "line"
                }; z.data.datasets[6] = { label: ["RevContent:0-7"], backgroundColor: "transparent", borderColor: "green", borderDash: [5, 5], data: w, type: "line" }; z.data.datasets[7] = { label: ["RevContent:8-21"], backgroundColor: "transparent", borderColor: "green", borderDash: [2, 2], data: x, type: "line" }; z.data.datasets[8] = { label: ["RevContent:22+"], backgroundColor: "transparent", borderColor: "green", data: y, type: "line" }; z.update(); m = l = k = h = g = f = e = d = b = 0; n = []; p = []; q = []; r = []; t =
                []; u = []; v = []; w = []; x = []; y = []; for (a = 0; a < c.Date.length; a++) "CA" == ajaxData.Country[a] && ("ContentAd" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (p[b] = [ajaxData.RPM[a]], n[b] = [ajaxData.Date[a]], b++), "ContentAd" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (q[d] = [ajaxData.RPM[a]], d++), "ContentAd" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (r[e] = [ajaxData.RPM[a]], e++), "MGID" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (t[f] = [ajaxData.RPM[a]], f++), "MGID" == ajaxData.Advertiser[a] &&
                "8-21" == ajaxData.AgeBucket[a] && (u[g] = [ajaxData.RPM[a]], g++), "MGID" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (v[h] = [ajaxData.RPM[a]], h++), "RevContent" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (w[k] = [ajaxData.RPM[a]], k++), "RevContent" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (x[l] = [ajaxData.RPM[a]], l++), "RevContent" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (y[m] = [ajaxData.RPM[a]], m++)); A.data.labels = n; A.data.datasets[0] = {
                    label: ["ContentAd:0-7"],
                    backgroundColor: "transparent", borderColor: "red", borderDash: [5, 5], data: p, type: "line"
                }; A.data.datasets[1] = { label: ["ContentAd:8-21"], backgroundColor: "transparent", borderColor: "red", borderDash: [2, 2], data: q, type: "line" }; A.data.datasets[2] = { label: ["ContentAd:22+"], backgroundColor: "transparent", borderColor: "red", data: r, type: "line" }; A.data.datasets[3] = { label: ["MGID:0-7"], backgroundColor: "transparent", borderColor: "blue", borderDash: [5, 5], data: t, type: "line" }; A.data.datasets[4] = {
                    label: ["MGID:8-21"], backgroundColor: "transparent",
                    borderColor: "blue", borderDash: [2, 2], data: u, type: "line"
                }; A.data.datasets[5] = { label: ["MGID:22+"], backgroundColor: "transparent", borderColor: "blue", data: v, type: "line" }; A.data.datasets[6] = { label: ["RevContent:0-7"], backgroundColor: "transparent", borderColor: "green", borderDash: [5, 5], data: w, type: "line" }; A.data.datasets[7] = { label: ["RevContent:8-21"], backgroundColor: "transparent", borderColor: "green", borderDash: [2, 2], data: x, type: "line" }; A.data.datasets[8] = {
                    label: ["RevContent:22+"], backgroundColor: "transparent",
                    borderColor: "green", data: y, type: "line"
                }; A.update(); m = l = k = h = g = f = e = d = b = 0; n = []; p = []; q = []; r = []; t = []; u = []; v = []; w = []; x = []; y = []; for (a = 0; a < c.Date.length; a++) "GB" == ajaxData.Country[a] && ("ContentAd" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (p[b] = [ajaxData.RPM[a]], n[b] = [ajaxData.Date[a]], b++), "ContentAd" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (q[d] = [ajaxData.RPM[a]], d++), "ContentAd" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (r[e] = [ajaxData.RPM[a]], e++), "MGID" == ajaxData.Advertiser[a] &&
                "0-7" == ajaxData.AgeBucket[a] && (t[f] = [ajaxData.RPM[a]], f++), "MGID" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (u[g] = [ajaxData.RPM[a]], g++), "MGID" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (v[h] = [ajaxData.RPM[a]], h++), "RevContent" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (w[k] = [ajaxData.RPM[a]], k++), "RevContent" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (x[l] = [ajaxData.RPM[a]], l++), "RevContent" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] &&
                (y[m] = [ajaxData.RPM[a]], m++)); B.data.labels = n; B.data.datasets[0] = { label: ["ContentAd:0-7"], backgroundColor: "transparent", borderColor: "red", borderDash: [5, 5], data: p, type: "line" }; B.data.datasets[1] = { label: ["ContentAd:8-21"], backgroundColor: "transparent", borderColor: "red", borderDash: [2, 2], data: q, type: "line" }; B.data.datasets[2] = { label: ["ContentAd:22+"], backgroundColor: "transparent", borderColor: "red", data: r, type: "line" }; B.data.datasets[3] = {
                    label: ["MGID:0-7"], backgroundColor: "transparent", borderColor: "blue",
                    borderDash: [5, 5], data: t, type: "line"
                }; B.data.datasets[4] = { label: ["MGID:8-21"], backgroundColor: "transparent", borderColor: "blue", borderDash: [2, 2], data: u, type: "line" }; B.data.datasets[5] = { label: ["MGID:22+"], backgroundColor: "transparent", borderColor: "blue", data: v, type: "line" }; B.data.datasets[6] = { label: ["RevContent:0-7"], backgroundColor: "transparent", borderColor: "green", borderDash: [5, 5], data: w, type: "line" }; B.data.datasets[7] = {
                    label: ["RevContent:8-21"], backgroundColor: "transparent", borderColor: "green", borderDash: [2,
                    2], data: x, type: "line"
                }; B.data.datasets[8] = { label: ["RevContent:22+"], backgroundColor: "transparent", borderColor: "green", data: y, type: "line" }; B.update(); m = l = k = h = g = f = e = d = b = 0; n = []; p = []; q = []; r = []; t = []; u = []; v = []; w = []; x = []; y = []; for (a = 0; a < c.Date.length; a++) "IN" == ajaxData.Country[a] && ("ContentAd" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (p[b] = [ajaxData.RPM[a]], n[b] = [ajaxData.Date[a]], b++), "ContentAd" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (q[d] = [ajaxData.RPM[a]], d++), "ContentAd" ==
                ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (r[e] = [ajaxData.RPM[a]], e++), "MGID" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (t[f] = [ajaxData.RPM[a]], f++), "MGID" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (u[g] = [ajaxData.RPM[a]], g++), "MGID" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (v[h] = [ajaxData.RPM[a]], h++), "RevContent" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (w[k] = [ajaxData.RPM[a]], k++), "RevContent" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] &&
                (x[l] = [ajaxData.RPM[a]], l++), "RevContent" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (y[m] = [ajaxData.RPM[a]], m++)); C.data.labels = n; C.data.datasets[0] = { label: ["ContentAd:0-7"], backgroundColor: "transparent", borderColor: "red", borderDash: [5, 5], data: p, type: "line" }; C.data.datasets[1] = { label: ["ContentAd:8-21"], backgroundColor: "transparent", borderColor: "red", borderDash: [2, 2], data: q, type: "line" }; C.data.datasets[2] = {
                    label: ["ContentAd:22+"], backgroundColor: "transparent", borderColor: "red", data: r,
                    type: "line"
                }; C.data.datasets[3] = { label: ["MGID:0-7"], backgroundColor: "transparent", borderColor: "blue", borderDash: [5, 5], data: t, type: "line" }; C.data.datasets[4] = { label: ["MGID:8-21"], backgroundColor: "transparent", borderColor: "blue", borderDash: [2, 2], data: u, type: "line" }; C.data.datasets[5] = { label: ["MGID:22+"], backgroundColor: "transparent", borderColor: "blue", data: v, type: "line" }; C.data.datasets[6] = { label: ["RevContent:0-7"], backgroundColor: "transparent", borderColor: "green", borderDash: [5, 5], data: w, type: "line" };
                C.data.datasets[7] = { label: ["RevContent:8-21"], backgroundColor: "transparent", borderColor: "green", borderDash: [2, 2], data: x, type: "line" }; C.data.datasets[8] = { label: ["RevContent:22+"], backgroundColor: "transparent", borderColor: "green", data: y, type: "line" }; C.update(); m = l = k = h = g = f = e = d = b = 0; n = []; p = []; q = []; r = []; t = []; u = []; v = []; w = []; x = []; y = []; for (a = 0; a < c.Date.length; a++) "Other" == ajaxData.Country[a] && ("ContentAd" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (p[b] = [ajaxData.RPM[a]], n[b] = [ajaxData.Date[a]],
                b++), "ContentAd" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (q[d] = [ajaxData.RPM[a]], d++), "ContentAd" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (r[e] = [ajaxData.RPM[a]], e++), "MGID" == ajaxData.Advertiser[a] && "0-7" == ajaxData.AgeBucket[a] && (t[f] = [ajaxData.RPM[a]], f++), "MGID" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (u[g] = [ajaxData.RPM[a]], g++), "MGID" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (v[h] = [ajaxData.RPM[a]], h++), "RevContent" == ajaxData.Advertiser[a] &&
                "0-7" == ajaxData.AgeBucket[a] && (w[k] = [ajaxData.RPM[a]], k++), "RevContent" == ajaxData.Advertiser[a] && "8-21" == ajaxData.AgeBucket[a] && (x[l] = [ajaxData.RPM[a]], l++), "RevContent" == ajaxData.Advertiser[a] && "22+" == ajaxData.AgeBucket[a] && (y[m] = [ajaxData.RPM[a]], m++)); D.data.labels = n; D.data.datasets[0] = { label: ["ContentAd:0-7"], backgroundColor: "transparent", borderColor: "red", borderDash: [5, 5], data: p, type: "line" }; D.data.datasets[1] = {
                    label: ["ContentAd:8-21"], backgroundColor: "transparent", borderColor: "red", borderDash: [2,
                    2], data: q, type: "line"
                }; D.data.datasets[2] = { label: ["ContentAd:22+"], backgroundColor: "transparent", borderColor: "red", data: r, type: "line" }; D.data.datasets[3] = { label: ["MGID:0-7"], backgroundColor: "transparent", borderColor: "blue", borderDash: [5, 5], data: t, type: "line" }; D.data.datasets[4] = { label: ["MGID:8-21"], backgroundColor: "transparent", borderColor: "blue", borderDash: [2, 2], data: u, type: "line" }; D.data.datasets[5] = { label: ["MGID:22+"], backgroundColor: "transparent", borderColor: "blue", data: v, type: "line" }; D.data.datasets[6] =
                { label: ["RevContent:0-7"], backgroundColor: "transparent", borderColor: "green", borderDash: [5, 5], data: w, type: "line" }; D.data.datasets[7] = { label: ["RevContent:8-21"], backgroundColor: "transparent", borderColor: "green", borderDash: [2, 2], data: x, type: "line" }; D.data.datasets[8] = { label: ["RevContent:22+"], backgroundColor: "transparent", borderColor: "green", data: y, type: "line" }; D.update()
            }, error: function () { console.log("Error") }
        })
    })()
});
